# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.3-j17)

    The version of the OpenAPI document: 1.3.3-SNAPSHOT
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from touroptimizer_py_client.api.read_database_download_encrypted_service_controller_api import ReadDatabaseDownloadEncryptedServiceControllerApi


class TestReadDatabaseDownloadEncryptedServiceControllerApi(unittest.TestCase):
    """ReadDatabaseDownloadEncryptedServiceControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReadDatabaseDownloadEncryptedServiceControllerApi()

    def tearDown(self) -> None:
        pass

    def test_download_encrypted_zipped_optimization(self) -> None:
        """Test case for download_encrypted_zipped_optimization

        Download decrypted optimization by id and creator. Only works, if connected to a database.
        """
        pass

    def test_download_encrypted_zipped_solution(self) -> None:
        """Test case for download_encrypted_zipped_solution

        Download decrypted solution by id and creator. Only works, if connected to a database.
        """
        pass


if __name__ == '__main__':
    unittest.main()
