image: maven:3.8.8-eclipse-temurin-17-alpine

pipelines:
  default:
    - step:
        name: Create JOpt Python Rest Example Sandbox
        services:
          - docker
        script:
          - cd ./sandbox/python/
          - myVersion=1.0 
          - docker version
          - docker build -t dnaevolutions/jopt_py_example_server:${myVersion} .
          - docker tag dnaevolutions/jopt_py_example_server:${myVersion} dnaevolutions/jopt_py_example_server:latest
          - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
          - docker push dnaevolutions/jopt_py_example_server:${myVersion}
          - docker push dnaevolutions/jopt_py_example_server:latest
definitions:
  services:
    docker:
      memory: 1024