"""
Search/list jobs in the database example.

Demonstrates how to query the TourOptimizer database for previously submitted
optimization jobs. Uses the JobApi's list_jobs endpoint (POST /api/v1/jobs/search)
with a DatabaseInfoSearch filter.

The search can filter by creator, ident, date range, and more. Results include
metadata (creator, ident, type, content_type, id) but not the full optimization.
Use the returned id with get_job_result to load the actual result (see loadFAF examples).

Prerequisites:
- A running TourOptimizer instance with database support.
- At least one job previously submitted (see the optimizeFAF example).

Usage:
    python examples/searchFAF/tour_optimizer_search_faf_example.py
"""

import json
from util.test_element_creator import  TestElementsCreator
from util.test_rest_optimization_creator import  TestRestOptimizationCreator
from util.test_position_input import TestPositionsInput
from util.tour_optimizer_endpoints import Endpoints
from util.tour_optimizer_rest_caller import TourOptimizerRestCaller
from util.test_faf_helper import TestFAFHelper
from pprint import pprint

from touroptimizer_py_client.models.database_info_search import DatabaseInfoSearch
from touroptimizer_py_client.models.database_info_search_result import DatabaseInfoSearchResult

from typing import List

def main():
    """Search for optimization jobs in the database by creator."""

    # Modify these variables as needed
    is_azure_call = False  # Set to True if using Azure, make sure a local docker container is running otherwise
    my_azure_api_key = None  # Empty key will be ignored
    tenant_id = "DEFAULT_TENANT"

    # Initialize TourOptimizer REST caller
    if is_azure_call:
        tour_optimizer_caller = TourOptimizerRestCaller(
            tour_optimizer_url=Endpoints.AZURE_SWAGGER_TOUROPTIMIZER_URL,
            azure_api_key=my_azure_api_key
        )
    else:
        tour_optimizer_caller = TourOptimizerRestCaller(
            tour_optimizer_url=Endpoints.LOCAL_SWAGGER_TOUROPTIMIZER_URL
        )



     # Not all fields are mandatory. The ident IS NOT equal to the id. The ident is
     # a user defined String to identify the optimization (it does NOT need to be
     # unique). The id is a unique string automatically generated by the database.
     #
     # JSON-Example: {
     #     "creator": "DEFAULT_DNA_CREATOR",
     #      "ident": "My-JOpt-Run",
     #     "limit": 10, "sortDirection": "DESC",
     #     "createdDateStart": "2023-05-10T09:11:38.445Z",
     #      "createdDateEnd": "2023-05-10T09:11:38.445Z",
     #     "timeOut": "PT1M"
     # }


    info_search = DatabaseInfoSearch()
    info_search.creator = "TEST_PY_FAF_CREATOR" # magic prefix "hash:" does work here!


    # List jobs matching the search criteria
    infos = tour_optimizer_caller.list_jobs(info_search, tenant_id=tenant_id);

    # Print result
    pprint(infos)


if __name__ == "__main__":
    main()
