import json
from util.test_element_creator import  TestElementsCreator
from util.test_rest_optimization_creator import  TestRestOptimizationCreator
from util.test_position_input import TestPositionsInput
from util.tour_optimizer_endpoints import Endpoints
from util.tour_optimizer_rest_caller import TourOptimizerRestCaller
from util.test_faf_helper import TestFAFHelper
from pprint import pprint

from touroptimizer_py_client.models.database_info_search import DatabaseInfoSearch
from touroptimizer_py_client.models.database_info_search_result import DatabaseInfoSearchResult

from typing import List

def main():
    """
    Example of using the TourOptimizer REST API in Python.
    """

    # Modify these variables as needed
    is_azure_call = False  # Set to True if using Azure, make sure a local docker container is running otherwise
    my_azure_api_key = None  # Empty key will be ignored
 
    # Initialize TourOptimizer REST caller
    if is_azure_call:
        tour_optimizer_caller = TourOptimizerRestCaller(
            tour_optimizer_url=Endpoints.AZURE_SWAGGER_TOUROPTIMIZER_URL,
            azure_api_key=my_azure_api_key
        )
    else:
        tour_optimizer_caller = TourOptimizerRestCaller(
            tour_optimizer_url=Endpoints.LOCAL_SWAGGER_TOUROPTIMIZER_URL
        )
        

     
     # Not all fields are mandatory. The ident IS NOT equal to the id. The ident is
     # a user defined String to identify the optimization (it does NOT need to be
     # unique). The id is a unique string automatically generated by the database.
     #
     # JSON-Example: { 
     #     "creator": "DEFAULT_DNA_CREATOR",
     #      "ident": "My-JOpt-Run",
     #     "limit": 10, "sortDirection": "DESC", 
     #     "createdDateStart": "2023-05-10T09:11:38.445Z",
     #      "createdDateEnd": "2023-05-10T09:11:38.445Z",
     #     "timeOut": "PT1M" 
     # }
    

    info_search = DatabaseInfoSearch()
    info_search.creator = "TEST_PY_FAF_CREATOR" # magic prefix "hash:" does work here!
    
    
    # content_type='application/x-bzip2' is indicating an unencrypted optimization
    # content_type='application/octet-stream' is indicating an encrypted optimization
    infos = tour_optimizer_caller.find_optimization_infos_in_database(info_search);
    
    # Print result
    pprint(infos)


if __name__ == "__main__":
    main()