# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.3-j17)

    The version of the OpenAPI document: 1.3.3-SNAPSHOT
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from touroptimizer_py_client.models.constraint_type import ConstraintType
from touroptimizer_py_client.models.type_level_requirement import TypeLevelRequirement
from typing import Optional, Set
from typing_extensions import Self

class BitTypeWithExpertiseConstraint(ConstraintType):
    """
    BitTypeWithExpertiseConstraint
    """ # noqa: E501
    dict_type_names: Optional[List[StrictStr]] = Field(default=None, description="A list of user-provided dict type-names. Those values will be mapped.", alias="dictTypeNames")
    dict_mapping: Optional[Dict[str, TypeLevelRequirement]] = Field(default=None, description="The mapping of a certain type. or multiple types", alias="dictMapping")
    info_cost_model: Optional[StrictStr] = Field(default=None, description="The cost model for matching the expertise.", alias="infoCostModel")
    type_name: StrictStr = Field(description="The typeName of the object", alias="typeName")
    is_hard_level: StrictBool = Field(description="Defines if a level of a cosntraint is soft contrained or hard constraint. A hard constraint is fullfilled by the architectural design of the Optimzer. Therefore a hard constraint violation cannot occure. However, not all constraints can be hard-constraint-", alias="isHardLevel")
    __properties: ClassVar[List[str]] = ["typeName", "dictTypeNames", "dictMapping", "infoCostModel", "isHardLevel"]

    @field_validator('info_cost_model')
    def info_cost_model_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PENALIZE_MATCHING_SKILL_HIGH_DELTA', 'PENALIZE_MATCHING_SKILL_PREFERRED_RESOURCE_HIGH_DELTA', 'PENALIZE_MATCHING_SKILL_LOW_DELTA', 'PENALIZE_MATCHING_SKILL_PREFERRED_RESOURCE_LOW_DELTA', 'NO_PENALIZE_MATCHING_SKILL']):
            raise ValueError("must be one of enum values ('PENALIZE_MATCHING_SKILL_HIGH_DELTA', 'PENALIZE_MATCHING_SKILL_PREFERRED_RESOURCE_HIGH_DELTA', 'PENALIZE_MATCHING_SKILL_LOW_DELTA', 'PENALIZE_MATCHING_SKILL_PREFERRED_RESOURCE_LOW_DELTA', 'NO_PENALIZE_MATCHING_SKILL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BitTypeWithExpertiseConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in dict_mapping (dict)
        _field_dict = {}
        if self.dict_mapping:
            for _key_dict_mapping in self.dict_mapping:
                if self.dict_mapping[_key_dict_mapping]:
                    _field_dict[_key_dict_mapping] = self.dict_mapping[_key_dict_mapping].to_dict()
            _dict['dictMapping'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BitTypeWithExpertiseConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "typeName": obj.get("typeName") if obj.get("typeName") is not None else 'BitTypeWithExpertise',
            "dictTypeNames": obj.get("dictTypeNames"),
            "dictMapping": dict(
                (_k, TypeLevelRequirement.from_dict(_v))
                for _k, _v in obj["dictMapping"].items()
            )
            if obj.get("dictMapping") is not None
            else None,
            "infoCostModel": obj.get("infoCostModel"),
            "isHardLevel": obj.get("isHardLevel")
        })
        return _obj


