# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-rc3-j17-SNAPSHOT)

    The version of the OpenAPI document: unknown
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from touroptimizer_py_client.models.connection_related_late_margin import ConnectionRelatedLateMargin
from touroptimizer_py_client.models.pillar_type import PillarType
from typing import Optional, Set
from typing_extensions import Self

class GeoPillarNode(PillarType):
    """
    GeoPillarNode
    """ # noqa: E501
    attached_resource_id: Optional[StrictStr] = Field(default=None, description="The attached resourceId. A geoPillar must be visited by this resource.", alias="attachedResourceId")
    only_scheduled_in_company: Optional[StrictBool] = Field(default=None, description="The onlyScheduledInCompany", alias="onlyScheduledInCompany")
    connection_related_late_margin: Optional[ConnectionRelatedLateMargin] = Field(default=None, alias="connectionRelatedLateMargin")
    type_name: StrictStr = Field(description="The typeName of the object", alias="typeName")
    is_forced_stay_node: Optional[StrictBool] = Field(default=None, description="The isForcedStayNode", alias="isForcedStayNode")
    is_schedulable_before_working_hours: Optional[StrictBool] = Field(default=None, description="The isSchedulableBeforeWorkingHours", alias="isSchedulableBeforeWorkingHours")
    is_overwriting_route_start: Optional[StrictBool] = Field(default=None, description="The boolean isOverwritingRouteStart. Instead of using the default start element of the route, the geoPillar will be used as so-called startAnchor.", alias="isOverwritingRouteStart")
    is_overwriting_route_termination: Optional[StrictBool] = Field(default=None, description="The boolean isOverwritingRouteTermination. Instead of using the default termination element of the route, the geoPillar will be used as so-called endAnchor.", alias="isOverwritingRouteTermination")
    is_time_adjustable_anchor: Optional[StrictBool] = Field(default=None, description="The isTimeAdjustableAnchor", alias="isTimeAdjustableAnchor")
    is_auto_transformable2_start_anchor: Optional[StrictBool] = Field(default=None, description="The isAutoTransformable2StartAnchor", alias="isAutoTransformable2StartAnchor")
    is_schedulable_after_working_hours: Optional[StrictBool] = Field(default=None, description="The isSchedulableAfterWorkingHours", alias="isSchedulableAfterWorkingHours")
    __properties: ClassVar[List[str]] = ["typeName", "attachedResourceId", "onlyScheduledInCompany", "connectionRelatedLateMargin", "isForcedStayNode", "isSchedulableBeforeWorkingHours", "isOverwritingRouteStart", "isOverwritingRouteTermination", "isTimeAdjustableAnchor", "isAutoTransformable2StartAnchor", "isSchedulableAfterWorkingHours"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeoPillarNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connection_related_late_margin
        if self.connection_related_late_margin:
            _dict['connectionRelatedLateMargin'] = self.connection_related_late_margin.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeoPillarNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "typeName": obj.get("typeName") if obj.get("typeName") is not None else 'GeoPillarNode',
            "attachedResourceId": obj.get("attachedResourceId"),
            "onlyScheduledInCompany": obj.get("onlyScheduledInCompany"),
            "connectionRelatedLateMargin": ConnectionRelatedLateMargin.from_dict(obj["connectionRelatedLateMargin"]) if obj.get("connectionRelatedLateMargin") is not None else None,
            "isForcedStayNode": obj.get("isForcedStayNode"),
            "isSchedulableBeforeWorkingHours": obj.get("isSchedulableBeforeWorkingHours"),
            "isOverwritingRouteStart": obj.get("isOverwritingRouteStart"),
            "isOverwritingRouteTermination": obj.get("isOverwritingRouteTermination"),
            "isTimeAdjustableAnchor": obj.get("isTimeAdjustableAnchor"),
            "isAutoTransformable2StartAnchor": obj.get("isAutoTransformable2StartAnchor"),
            "isSchedulableAfterWorkingHours": obj.get("isSchedulableAfterWorkingHours")
        })
        return _obj


