# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (null)

    The version of the OpenAPI document: 1.2.6-SNAPSHOT
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from touroptimizer_py_client.models.creator_setting import CreatorSetting
from touroptimizer_py_client.models.optimization_key_setting import OptimizationKeySetting
from touroptimizer_py_client.models.optimization_persistence_setting import OptimizationPersistenceSetting
from touroptimizer_py_client.models.plugin_settings import PluginSettings
from touroptimizer_py_client.models.text_solution import TextSolution
from typing import Optional, Set
from typing_extensions import Self

class JSONConfig(BaseModel):
    """
    The extension of the configuration. For example, to provide a license.
    """ # noqa: E501
    creator_setting: Optional[CreatorSetting] = Field(default=None, alias="creatorSetting")
    text_solution: Optional[TextSolution] = Field(default=None, alias="textSolution")
    key_setting: Optional[OptimizationKeySetting] = Field(default=None, alias="keySetting")
    persistence_setting: Optional[OptimizationPersistenceSetting] = Field(default=None, alias="persistenceSetting")
    plugin_settings: Optional[PluginSettings] = Field(default=None, alias="pluginSettings")
    time_out: Optional[StrictStr] = Field(default=None, description="The timeout for the optimization run.", alias="timeOut")
    __properties: ClassVar[List[str]] = ["creatorSetting", "textSolution", "keySetting", "persistenceSetting", "pluginSettings", "timeOut"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JSONConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creator_setting
        if self.creator_setting:
            _dict['creatorSetting'] = self.creator_setting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of text_solution
        if self.text_solution:
            _dict['textSolution'] = self.text_solution.to_dict()
        # override the default output from pydantic by calling `to_dict()` of key_setting
        if self.key_setting:
            _dict['keySetting'] = self.key_setting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of persistence_setting
        if self.persistence_setting:
            _dict['persistenceSetting'] = self.persistence_setting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of plugin_settings
        if self.plugin_settings:
            _dict['pluginSettings'] = self.plugin_settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JSONConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creatorSetting": CreatorSetting.from_dict(obj["creatorSetting"]) if obj.get("creatorSetting") is not None else None,
            "textSolution": TextSolution.from_dict(obj["textSolution"]) if obj.get("textSolution") is not None else None,
            "keySetting": OptimizationKeySetting.from_dict(obj["keySetting"]) if obj.get("keySetting") is not None else None,
            "persistenceSetting": OptimizationPersistenceSetting.from_dict(obj["persistenceSetting"]) if obj.get("persistenceSetting") is not None else None,
            "pluginSettings": PluginSettings.from_dict(obj["pluginSettings"]) if obj.get("pluginSettings") is not None else None,
            "timeOut": obj.get("timeOut")
        })
        return _obj


