# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.3-j17)

    The version of the OpenAPI document: 1.3.3-SNAPSHOT
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from touroptimizer_py_client.models.constraint_type import ConstraintType
from typing import Optional, Set
from typing_extensions import Self

class MagnetoNodeConstraint(ConstraintType):
    """
    MagnetoNodeConstraint
    """ # noqa: E501
    node_magnet_ids: List[StrictStr] = Field(description="A list of user-provided node-magntet-ids. Attraction Mode: A node holding this constraints attracts nodes (defined via ids) to share the same route. Repulsive mode: A node holding this constraints repels nodes (defined via ids).", alias="nodeMagnetIds")
    order: StrictStr = Field(description="The desired order. For example, if desired node order is front, the node carrying the constraint is ideally in front of the other nodes defined in nodeMagnetIds.")
    type_name: StrictStr = Field(description="The typeName of the object", alias="typeName")
    is_attracting_magnet: StrictBool = Field(description="True: Attracting nodes. False: Repel nodes.", alias="isAttractingMagnet")
    __properties: ClassVar[List[str]] = ["typeName", "nodeMagnetIds", "order", "isAttractingMagnet"]

    @field_validator('order')
    def order_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NO_ORDER', 'FRONT', 'BACK']):
            raise ValueError("must be one of enum values ('NO_ORDER', 'FRONT', 'BACK')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MagnetoNodeConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MagnetoNodeConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "typeName": obj.get("typeName") if obj.get("typeName") is not None else 'MagnetoNode',
            "nodeMagnetIds": obj.get("nodeMagnetIds"),
            "order": obj.get("order"),
            "isAttractingMagnet": obj.get("isAttractingMagnet")
        })
        return _obj


