# coding: utf-8

"""
    DNA Evolutions - JOpt.TourOptimizer

    This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-rc3-j17-SNAPSHOT)

    The version of the OpenAPI document: unknown
    Contact: info@dna-evolutions.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from touroptimizer_py_client.models.long_long_pair import LongLongPair
from typing import Optional, Set
from typing_extensions import Self

class OpeningHours(BaseModel):
    """
    The list of non-overlapping openingHours of the nodes.
    """ # noqa: E501
    begin: datetime = Field(description="The begin of the Opening Hour")
    end: datetime = Field(description="The end of the Opening Hour")
    zone_id: StrictStr = Field(description="The zoneId of the Opening Hour", alias="zoneId")
    service_hours_offsets: Optional[List[LongLongPair]] = Field(default=None, description="The serviceHoursOffsets", alias="serviceHoursOffsets")
    is_preffered: Optional[StrictBool] = Field(default=False, description="The isPreffered boolean. If an Opening Hour is preffered the Optimizer will try to visit the node inside this Opening Hour. By default, the first Openinghour of a node is the preffered opening hour.", alias="isPreffered")
    is_solo_access_hours: Optional[StrictBool] = Field(default=False, description="The isSoloAccessHours", alias="isSoloAccessHours")
    __properties: ClassVar[List[str]] = ["begin", "end", "zoneId", "serviceHoursOffsets", "isPreffered", "isSoloAccessHours"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpeningHours from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in service_hours_offsets (list)
        _items = []
        if self.service_hours_offsets:
            for _item_service_hours_offsets in self.service_hours_offsets:
                if _item_service_hours_offsets:
                    _items.append(_item_service_hours_offsets.to_dict())
            _dict['serviceHoursOffsets'] = _items
        # set to None if is_preffered (nullable) is None
        # and model_fields_set contains the field
        if self.is_preffered is None and "is_preffered" in self.model_fields_set:
            _dict['isPreffered'] = None

        # set to None if is_solo_access_hours (nullable) is None
        # and model_fields_set contains the field
        if self.is_solo_access_hours is None and "is_solo_access_hours" in self.model_fields_set:
            _dict['isSoloAccessHours'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpeningHours from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "begin": obj.get("begin"),
            "end": obj.get("end"),
            "zoneId": obj.get("zoneId"),
            "serviceHoursOffsets": [LongLongPair.from_dict(_item) for _item in obj["serviceHoursOffsets"]] if obj.get("serviceHoursOffsets") is not None else None,
            "isPreffered": obj.get("isPreffered") if obj.get("isPreffered") is not None else False,
            "isSoloAccessHours": obj.get("isSoloAccessHours") if obj.get("isSoloAccessHours") is not None else False
        })
        return _obj


